server:
  port: 2002

spring:
  application:
    name: seata-storage-servcie
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml